name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-validate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform FMT
        run: terraform -chdir=modules/nginx fmt -check

      - name: Terraform INIT & VALIDATE
        run: |
          terraform -chdir=modules/nginx init -backend=false
          terraform -chdir=modules/nginx validate

      - name: Terraform Lint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          tflint --init
          tflint --chdir=modules/nginx

      - name: Generate module documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ./modules/nginx
          output-file: README.md
          output-method: replace
          git-push: "true"
