name: e2e
on:
  push:
    branches: [main]
  pull_request:
jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - uses: helm/kind-action@v1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=examples/basic_usage init
      - run: terraform -chdir=examples/basic_usage validate
      - run: go test ./test -v -timeout 30m

